name: CI with Spring Boot 2.x

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  build:
    name: Test with ${{ matrix.spring-boot-version }} on JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11, 17, 21, 22]
        distribution: ['zulu']
        spring-boot-version: ['2.7', '2.6']
      fail-fast: false
      max-parallel: 8
    steps:
      - uses: actions/checkout@v4
      - name: Set JDK from jdk.java.net
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: ${{ matrix.java }}
        if: ${{ matrix.java != '11' && matrix.java != '17' }}
      - name: Set up older JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
        if: ${{ matrix.java == '11' || matrix.java == '17' }}
      - name: Show a Java version
        run: java -version
      - name: Verify a compatibility
        run: ./verify.sh ${{ matrix.spring-boot-version }}
