name: CI with Spring Boot 2.x

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  build:
    name: Test with ${{ matrix.spring-boot-version }} on JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 17, 18]
        distribution: ['zulu']
        spring-boot-version: ['2.7', '2.6', '2.5', '2.4', '2.3']
      fail-fast: false
      max-parallel: 8
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Show a Java version
        run: java -version
      - name: Verify a compatibility
        run: ./verify.sh ${{ matrix.spring-boot-version }} ${{ matrix.java }}
