name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  build:
    name: Test JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11, 17, 18-ea]
        distribution: ['zulu']
      fail-fast: false
      max-parallel: 4
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Show a Java version
        run: java -version
      - name: Verify a compatibility
        run: ./verify.sh
